---
# tasks file for hello
- name: Some dummy tasks
  ping:

- name: Environment print
  debug:
    msg: "{{ ansible_env }}"

- name: Download bootstrap.py from satellite_url
  get_url:
    url: "{{ satellite_url }}/pub"
    dest: /root/bootstrap.py
    validate_certs: false
    mode: '0540'

- name: Register with Satellite
  command: "/root/bootstrap.py -l {{ satellite_user }} -p {{ satellite_password | quote }} -s {{ satellite_url }} -o {{ satellite_organization | quote }} -L {{ satellite_location | quote }} -g {{ satellite_hostgroup | quote }} -a {{ satellite_activationkey | quote }}"

- name: Register for content from Satellite
  redhat_subscription:
    state: present
    activationkey: "{{ satellite_activationkey }}"
    ord_id: "{{ satellite_organization }}"
    auto_attach: true